# Generated by Django 5.2 on 2025-05-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=15)),
                ('tipo_empleo', models.CharField(choices=[('1', 'Relación de dependencia'), ('2', 'Independiente')], max_length=1)),
                ('antiguedad_laboral', models.PositiveIntegerField(help_text='En años')),
                ('bruto', models.PositiveIntegerField(help_text='Ingreso bruto mensual')),
                ('propiedad', models.PositiveIntegerField(help_text='Valor de la propiedad')),
                ('ahorros', models.PositiveIntegerField()),
                ('plazo', models.PositiveIntegerField(help_text='Plazo en años')),
            ],
            options={
                'db_table': 'consultas',
            },
        ),
    ]
